// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  htmlCss: [{ type: 'autogenerated', dirName: 'html-css' }],
  leetcode: [{ type: 'autogenerated', dirName: 'data-structures-and-algorithms/leetcode' }],
}

module.exports = sidebars
