// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  htmlCss: [{ type: 'autogenerated', dirName: 'html_css' }],
  leetcode: [{ type: 'autogenerated', dirName: 'data_structures_and_algorithms/leetcode' }],
}

module.exports = sidebars
